rtc: zynqmp: fix linking failure for ARCH arm
commit 5494f6703c7e71fcca8862e7bdfb28825fe17ee1 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

64-bit division "(u64 A) / (u32 B)" will break linking on ARCH arm:

rm-linux-gnueabihf-ld: drivers/rtc/rtc-zynqmp.o:
in function `xlnx_rtc_read_offset':
rtc-zynqmp.c:(.text+0x48): undefined reference to `__aeabi_ldivmod'

Fix this by using do_div.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Shubhrajyoti Datta <shubhrajyoti.datta@xilinx.com>
Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>