v4l: xilinx: sdi: Fix the uapi header license
commit 947476056df3d68a714b515977d8b4de69c3a0ed from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>