drm/i2c: adv7511: add missing include to drm/drm_probe_helper.h
commit  5d53c7b06ebe2aa392ec0d42ef45c7a24d9c1acb from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10

Otherwise, the compiler complains about not being able to find the
`drm_helper_hpd_irq_event` symbol:

```
drivers/gpu/drm/i2c/adv7511.c: In function 'adv7511_irq_process':
drivers/gpu/drm/i2c/adv7511.c:450:3: error: implicit declaration of function 'drm_helper_hpd_irq_event' [-Werror=implicit-function-declaration]
  450 |   drm_helper_hpd_irq_event(adv7511->encoder->dev);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Florian Klink <flokli@flokli.de>
Reviewed-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>