v4l: xilinx: dprx: Fix compilation error
commit 87b4984e62e20645b71c10cf1aa89518e4210261 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.6

This patch fixes the below compilation error with DisplayPort Rx driver
when debug is enabled.

In file included from <command-line>:
drivers/media/platform/xilinx/xilinx-dprxss.c: In function
‘xdprxss_clrset.constprop’:
././include/linux/compiler_types.h:322:45: error: call to
‘__compiletime_assert_503’ declared with attribute error: FIELD_PREP:
mask is not constant
  322 |         _compiletime_assert(condition, msg, __compiletime_assert_,
__COUNTER__)
      |                                             ^
././include/linux/compiler_types.h:303:25: note: in definition of macro
‘__compiletime_assert’
  303 |                         prefix ## suffix();                     \
      |                         ^~~~~~
././include/linux/compiler_types.h:322:9: note: in expansion of macro
‘_compiletime_assert’
  322 |         _compiletime_assert(condition, msg, __compiletime_assert_,
__COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:39:37: note: in expansion of macro
‘compiletime_assert’
   39 | #define BUILD_BUG_ON_MSG(cond, msg)
compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
./include/linux/bitfield.h:46:17: note: in expansion of macro
‘BUILD_BUG_ON_MSG’
   46 |                 BUILD_BUG_ON_MSG(!__builtin_constant_p(_mask),  \
      |                 ^~~~~~~~~~~~~~~~
./include/linux/bitfield.h:94:17: note: in expansion of macro
‘__BF_FIELD_CHECK’
   94 |                 __BF_FIELD_CHECK(_mask, 0ULL, _val,
"FIELD_PREP: "); \
      |                 ^~~~~~~~~~~~~~~~
drivers/media/platform/xilinx/xilinx-dprxss.c:597:19: note: in expansion
of macro ‘FIELD_PREP’
  597 |         regval |= FIELD_PREP(clr_mask, set_data);
      |                   ^~~~~~~~~~

Signed-off-by: Rajesh Gugulothu <gugulothu.rajesh@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>