misc: xilinx-ai-engine: Make direct writes to sysfs export buffers
commit 27a9b77ac59d575dc4226b9e58e99ef4b3e0e9fb from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

This patch fixes the below warnings by making direct writes to the sysfs
export buffers rather than allocating local stack buffers and then
copying them to the export buffers.

drivers/misc/xilinx-ai-engine/ai-engine-sysfs-event.c:126:1: error: the frame size of 2384 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
  126 | }
      | ^

Signed-off-by: Nishad Saraf <nishads@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>