drivers: remoteproc: xlnx: Fix uninitialized tcm mode
commit c7be61b38f39be620ede3867b77e82db7f8d7d08 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.6

Add "else" case for default tcm mode to silent following static check:

zynqmp_r5_cluster_init()
 error: uninitialized symbol 'tcm_mode'.

Fixes: a6b974b40f94 ("drivers: remoteproc: xlnx: Add Versal and Versal-NET support")
Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>
Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Link: https://lore.kernel.org/r/20240424163344.1344304-1-tanmay.shah@amd.com
Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>
State: upstream (b9511056ce5b)
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>