v4l: xilinx: events: Fix the uapi header license
commit 74011b0eb3732fac0bc547201fccdfdff18b309a from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>