drm: xlnx: hdcp: Fix incompatible typecast error
commit c4bed321068d47d871741bbe3bca64a6ecc3dddc from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.6

ntohll macro defines be64_to_cpu by typecasting input u64 data as
(__b64 *) which is wrong, driver no need to typecast it again as
be64_to_cpu macro itself will take care of it.

So, removed ntohll macro and replaced directly with be64_to_cpu pre-
defined macro in xdptx_hdcp1x_keymgmt_set_key() in order to resolve
below error for allmodconfig.

error: drivers/gpu/drm/xlnx/hdcp/xlnx_hdcp1x_keymngt.c:41:31: error: cast
to pointer from integer of different size [-Werror=int-to-pointer-cast]
   41 | #define ntohll be64_to_cpu((__be64 *)x)
      |                               ^
./include/uapi/linux/swab.h:128:54: note: in definition of macro
'__swab64'
  128 | #define _swab64 (u64)builtin_bswap64((_u64))

Signed-off-by: Lakshmi Prasanna Eachuri <lakshmi.prasanna.eachuri@amd.com>
Reviewed-by: Radhey Shyam Pandey <radhey.shyam.pandey@amd.com>
Message-ID: <1725631163-24247-5-git-send-email-lakshmi.prasanna.eachuri@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>