misc: xilinx_flex: Fix the lock definitions
commit  0957758636c6fe69385117b4393dfa0b4b2e9a76 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.4

First, it's defined as 'mutex' in struct while used by 'lock'. The build
failed because of name mismatch.

drivers/misc/xilinx_flex_pm.c:601:20: error: 'struct xflex_dev_info' has no member named 'mutex'
  601 |  mutex_init(&flexpm->mutex);
        |                    ^~

Then the lock scope was not correct, as it was never locked but unlocked
on exit. Based on description, hold the lock in the beginning of sysfs
entry point, then unlock before return.

While at it, add the description for 'mutex' in struct.

Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Reported-by: Florian Klink <flokli@flokli.de>
Cc: Shubhrajyoti Datta <shubhrajyoti.datta@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>