net: xilinx: Update Kconfig to select XILINX_AXI_EMAC for XILINX_TSN
commit d1232ae1d8c404ee6facc93f7912296648084d6e from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.15

With the existing implementation when linux kernel is built with
allmodconfig, several errors like following are reported.

drivers/net/ethernet/xilinx/xilinx_tsn_ep.o: in function `tsn_ep_xmit':
xilinx_tsn_ep.c.text+0x21c): undefined reference to `axienet_queue_xmit'

This patch updates Kconfig to ensure that when Xilinx TSN related files
are built as module(s), Xilinx Axi Ethernet driver is also pulled in, so
that symbols from Axi Ethernet driver are visible in Xilinx TSN module(s).

Signed-off-by: Anirudha Sarangi <anirudha.sarangi@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>