remoteproc: zynq_remoteproc: Revise to work with 5.10 kernel
commit  04064ddceeb90019f03822a9160736a66bc20162 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10

As there were changes in GIC and SMP, update remoteproc zynq driver so that
SGIs can work with upstream IRQ registration and send/recv mechanisms.

Signed-off-by: Ben Levinsky <ben.levinsky@xilinx.com>
Reviewed-by: Wendy Liang <wendy.liang@xilinx.com>
State: not-upstreamable
[Quanyang:
commit 64a1b95bb9fe ("genirq: Restrict export of irq_to_desc()") removed
the export of irq_to_desc(), but zynq_remoteproc.c is still using it.
This leads to a build failure:
ERROR: modpost: "irq_to_desc" [drivers/remoteproc/zynq_remoteproc.ko] undefined!
Fix it by exporting irq_to_desc when CONFIG_ZYNQ_REMOTEPROC is enabled.
]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>