usb: gadget: udc-xilinx: fix compilation error
commit 8ecb6029436c0ae23a5e66f6ba095fae4d489d64 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v6.1

This patch fixed below complation error for zynq platform.
Replaced __memcpy_toio method with memcpy_toioto support both
platform zynq and zu+.

Error: implicit declaration of function '__memcpy_toio

Signed-off-by: Piyush Mehta <piyush.mehta@amd.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>